[tool.isort]
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true
line_length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]  # Enable common error & formatting rules
ignore = ["E501"]  # Ignore line length violations

[tool.mypy]

[[tool.mypy.overrides]]
module = ["llama_index.*", "pydantic.*", "tenacity.*", "numpy.*", "pandas.*", "dotenv.*", "langchain.*", "langchain_core.*"]
ignore_missing_imports = true


[tool.black]
line_length = 88
target_version = ['py38', 'py39', 'py310']